name: CI Workflow
run-name: ${{ github.actor }} is building and testing the wiki
on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload your site output
        uses: withastro/action@v1
        with:
          node-version: '21.1.0'
